version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: []
    target-branch: deps
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels: []
    open-pull-requests-limit: 10
    target-branch: deps
